### ISSUE TITLE
Iterate over columns

### ISSUE THREAD

**Issue by alper** [antonmarsden/toodee#16]
I can't find in the documentation anywhere how you would iterate over columns.

Here on GitHub it says there's a `col()` function which I'll try but why not just call it `cols()`?

**Comment by antonmarsden** [comment]
You can use `col()` to iterate over a specific column. There's no `cols()` because it's a row-major implementation of a 2D array.
To iterate over each column, just use a loop, i.e., (pseudo code),
`for (i from 0 to num_cols - 1) {
  columnIter = col(i)
  ...
}`
