### ISSUE TITLE
Add serde support

### ISSUE THREAD

**Issue by KeyboardDanni** [antonmarsden/toodee#17]
I'd like to be able to serialize and deserialize 2D arrays using serde. While a [workaround](https://serde.rs/remote-derive.html) exists, official support would be more convenient.

Should be fairly straightforward, it's just a Vec and two usize. The default impls should work fine.

**Comment by cosmicchipsocket** [comment]
Just realized that we'd probably need more than the default impl since we'd need to validate the size of the data relative to the row and column counts. Ideally if this check fails it should return an error instead of panicking.

**Comment by antonmarsden** [comment]
@KeyboardDanni Thanks for raising this, I have added serde support in v0.4.2
