### ISSUE TITLE
Integer overflow could lead to undefined behaviour.

### ISSUE THREAD

**Issue by SamuelMcGowan** [antonmarsden/toodee#19]
I've only checked the `view` module, but I suspect this happens elsewhere, since the arithmetic doesn't seem to be checked.

Anyway, multiplying the width and height, if it overflowed, would cause the slice of the data to be smaller than expected, which would lead to undefined behaviour when trying to access data outside the slice.

**Comment by antonmarsden** [comment]
@SamuelMcGowan Thanks, working on this.

**Comment by antonmarsden** [comment]
Improvements made in 0.4.1 to identify overflows at array creation time.
